trigger:
 - main

pool:
  vmImage: ubuntu-latest

variables:
 stagename: 'stageterraform'

parameters:
  - name: city
    default: canadacentral
    values:
      - canadacentral
      - eastus3
      - westus3
stages:
  - stage: buildstage
    jobs:
      - job: buildjob
        steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(agent.builddirectory)'
            Contents: '**'
            TargetFolder: '$(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
            MaxArtifactSize: 1
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'




