trigger:
 - main
pool
 vmimage:ubuntu-latest
stages:
  - stage: stageterraform
    jobs:
      - job: jobterraform
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'prac2024'
              backendAzureRmResourceGroupName: 'rg_terraform_pipelin'
              backendAzureRmStorageAccountName: 'kishanstorageaccount123'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-var-file="dev.tfvars"'
              environmentServiceNameAzureRM: 'prac2024'