trigger:
 - main

pool:
  vmImage: ubuntu-latest

variables:
 stagename: 'stageterraform'

parameters:
  - name: city
    default: canadacentral
    values:
      - canadacentral
      - eastus3
      - westus3

stages:
  - stage: stageterraform
    jobs:
      - job: jobterraform
        steps:
          - template: steps.yaml
      - job: jobterraform2
        dependsOn: jobterraform
       # condition: failed()
        steps:
          - template: steps2.yaml
         